CREATE TABLE IF NOT EXISTS USUARIO (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL,
    NOME TEXT NOT NULL,
    BIO TEXT
);

CREATE TABLE IF NOT EXISTS OBRA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITULO TEXT NOT NULL,
    CONTEUDO TEXT NOT NULL,
    AUTOR TEXT NOT NULL,
    CONSTRAINT FK_OBRA_AUTOR FOREIGN KEY (AUTOR) REFERENCES USUARIO(USERNAME)
);

CREATE TABLE IF NOT EXISTS COMENTARIO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    OBRA_ID INTEGER NOT NULL,
    AUTOR TEXT NOT NULL,
    TEXTO TEXT NOT NULL,
    CONSTRAINT FK_COMENTARIO_OBRA FOREIGN KEY (OBRA_ID) REFERENCES OBRA(ID),
    CONSTRAINT FK_COMENTARIO_AUTOR FOREIGN KEY (AUTOR) REFERENCES USUARIO(USERNAME)
);

CREATE TABLE IF NOT EXISTS AVALIACAO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    OBRA_ID INTEGER NOT NULL,
    AVALIADOR TEXT NOT NULL,
    NOTA INTEGER NOT NULL CHECK (NOTA >= 0 AND NOTA <= 10),
    CONSTRAINT FK_AVALIACAO_OBRA FOREIGN KEY (OBRA_ID) REFERENCES OBRA(ID),
    CONSTRAINT FK_AVALIACAO_AVALIADOR FOREIGN KEY (AVALIADOR) REFERENCES USUARIO(USERNAME)
);